export const TRANSLATIONS = {
  uz: {
    nav: { home: "Bosh sahifa", products: "Mahsulotlar", news: "Yangiliklar", gallery: "Galereya", jobs: "Ish o'rinlari", contact: "Bog'lanish", admin: "Admin", menu: "Menyuni ochish", close: "Menyuni yopish" },
    hero: { title: "Yetakchi farmatsevtika kompaniyasiga xush kelibsiz", subtitle: "Zamonaviy ishlab chiqarish, GMP standartlari va xalqaro bozorga mos mahsulotlar.", cta1: "Ko'proq ma'lumot", cta2: "Bog'lanish", eyebrow: "MERRYMED FARM" },
    home: { about_eyebrow: "Rasmiy saytimizga xush kelibsiz", about_title: "Rasmiy saytimizga xush kelibsiz!", about_text: "MERRYMED FARM 2010 yilda tashkil etilgan bo'lib, ishlab chiqarish, saqlash, logistika va marketing jarayonlarini o'z ichiga olgan yirik farmatsevtika korxonalaridan biridir.", mission: "Dunyo talablariga javob beruvchi dori vositalarini ishlab chiqarish orqali ichki bozorni sifatli mahsulotlar bilan ta'minlash.", highlights_eyebrow: "Afzalliklar", highlights_title: "Bizning kuchli tomonlarimiz", products_eyebrow: "Mahsulotlar", products_title: "Asosiy toifalar", see_all: "Barchasini ko'rish", news_eyebrow: "Yangiliklar", news_title: "So'nggi yangilanishlar", go_news: "Yangiliklarga o'tish", gallery_eyebrow: "Galereya", gallery_title: "Ishlab chiqarishdan lavhalar", more: "Ko'proq" },
    highlights: [ {title: "Zamonaviy qadoqlash", text: "Saqlanish va xavfsizlikni ta'minlovchi yechimlar."}, {title: "Yangi texnologiyalar", text: "GMP talablariga javob beruvchi uskunalar."}, {title: "Noyob yondashuv", text: "Professionallikka asoslangan boshqaruv."} ],
    pages: { products: { title: "Mahsulotlar", subtitle: "Dori shakllari va toifalar." }, news: { title: "Yangiliklar", subtitle: "Kompaniya yangiliklari va e'lonlar." }, gallery: { title: "Galereya", subtitle: "Ishlab chiqarish lavhalar." }, jobs: { title: "Ish o'rinlari", subtitle: "Ochiq vakansiyalar." }, contact: { title: "Bog'lanish", subtitle: "Murojaat va hamkorlik uchun." } },
    jobs: [ {title: "QA mutaxassisi", location: "Namangan", type: "Full-time"}, {title: "Frontend developer", location: "Toshkent / Remote", type: "Contract"}, {title: "Logistika koordinatori", location: "Namangan", type: "Full-time"} ],
    contact: { eyebrow: "Bog'lanish", title: "Biz bilan aloqaga chiqing", name: "Ismingiz", email: "Email", message: "Xabar matni", send: "Yuborish", sent: "Xabaringiz yuborildi!", error: "Xatolik yuz berdi.", index: "Indeks", email_label: "Email", all: "Barchasi", apply: "Ariza topshirish" },
    footer: { about: "MERRYMED FARM - Zamonaviy farmatsevtika kompaniyasi.", contact: "Aloqa", rights: "© 2026 MERRYMED FARM. Barcha huquqlar himoyalangan.", old: "ZeroEndTech jamosi tomonidan yaratolgan" },
    admin: { title: "Admin Panel", login: "Kirish", logout: "Chiqish", products: "Mahsulotlar", news: "Yangiliklar", gallery: "Galereya", add: "Qo'shish", edit: "Tahrirlash", delete: "O'chirish", save: "Saqlash", cancel: "Bekor qilish", confirm: "Ishonchingiz komilmi?", email: "Email", password: "Parol", loginFail: "Email yoki parol noto'g'ri" }
  },
  ru: {
    nav: { home: "Главная", products: "Продукция", news: "Новости", gallery: "Галерея", jobs: "Вакансии", contact: "Контакты", admin: "Админ", menu: "Открыть меню", close: "Закрыть меню" },
    hero: { title: "ДОБРО ПОЖАЛОВАТЬ в ВЕДУЩУЮ ФАРМАЦЕВТИЧЕСКУЮ КОМПАНИЮ", subtitle: "Современное производство, стандарты GMP и продукция международного уровня.", cta1: "Подробнее", cta2: "Связаться", eyebrow: "MERRYMED FARM" },
    home: { about_eyebrow: "Добро пожаловать на официальный сайт", about_title: "Добро пожаловать на наш сайт!", about_text: "MERRYMED FARM основана в 2010 году и является одной из крупнейших фармацевтических компаний, охватывающих производство, хранение, логистику и маркетинг.", mission: "Производство лекарств мирового уровня для обеспечения внутреннего рынка качественной продукцией.", highlights_eyebrow: "Преимущества", highlights_title: "Наши сильные стороны", products_eyebrow: "Продукция", products_title: "Основные категории", see_all: "Смотреть все", news_eyebrow: "Новости", news_title: "Последние обновления", go_news: "Перейти к новостям", gallery_eyebrow: "Галерея", gallery_title: "Моменты производства", more: "Больше" },
    highlights: [ {title: "Современная упаковка", text: "Решения, обеспечивающие сохранность и безопасность."}, {title: "Новые технологии", text: "Оборудование по стандартам GMP."}, {title: "Уникальный подход", text: "Управление на основе профессионализма."} ],
    pages: { products: { title: "Продукция", subtitle: "Лекарственные формы и категории." }, news: { title: "Новости", subtitle: "Новости и объявления компании." }, gallery: { title: "Галерея", subtitle: "Моменты производства." }, jobs: { title: "Вакансии", subtitle: "Открытые позиции." }, contact: { title: "Контакты", subtitle: "Для обращений и сотрудничества." } },
    jobs: [ {title: "QA специалист", location: "Наманган", type: "Full-time"}, {title: "Frontend разработчик", location: "Ташкент / Remote", type: "Contract"}, {title: "Координатор логистики", location: "Наманган", type: "Full-time"} ],
    contact: { eyebrow: "Контакты", title: "Свяжитесь с нами",  name: "Ваше имя", email: "Email", message: "Сообщение", send: "Отправить", sent: "Сообщение отправлено!", error: "Произошла ошибка.", index: "Индекс", email_label: "Email", all: "Все", apply: "Подать заявку" },
    footer: { about: "MERRYMED FARM - Современная фармкомпания.", contact: "Контакты", rights: "© 2026 MERRYMED FARM. Все права защищены.", old:"Создано командой ZeroEndTech" },
    admin: { title: "Админ панель", login: "Войти", logout: "Выход", products: "Продукция", news: "Новости", gallery: "Галерея", add: "Добавить", edit: "Изменить", delete: "Удалить", save: "Сохранить", cancel: "Отмена", confirm: "Вы уверены?", email: "Email", password: "Пароль", loginFail: "Неверный email или пароль" }
  },
  en: {
    nav: { home: "Home", products: "Products", news: "News", gallery: "Gallery", jobs: "Careers", contact: "Contact", admin: "Admin", menu: "Open menu", close: "Close menu" },
    hero: { title: "Welcome to a Leading Pharmaceutical Company", subtitle: "Modern manufacturing, GMP standards, and international-grade products.", cta1: "Learn more", cta2: "Contact us", eyebrow: "MERRYMED FARM" },
    home: { about_eyebrow: "Welcome to our official website", about_title: "Welcome to our official website!", about_text: "MERRYMED FARM was founded in 2010 and is one of the largest pharmaceutical companies covering manufacturing, storage, logistics, and marketing.", mission: "Producing world-class medicines to supply the domestic market with quality products.", highlights_eyebrow: "Advantages", highlights_title: "Our strengths", products_eyebrow: "Products", products_title: "Main categories", see_all: "View all", news_eyebrow: "News", news_title: "Latest updates", go_news: "Go to news", gallery_eyebrow: "Gallery", gallery_title: "Production moments", more: "More" },
    highlights: [ {title: "Modern packaging", text: "Solutions for safety and preservation."}, {title: "New technologies", text: "Equipment meeting GMP standards."}, {title: "Unique approach", text: "Management based on professionalism."} ],
    pages: { products: { title: "Products", subtitle: "Dosage forms and categories." }, news: { title: "News", subtitle: "Company news and announcements." }, gallery: { title: "Gallery", subtitle: "Production moments." }, jobs: { title: "Careers", subtitle: "Open positions." }, contact: { title: "Contact", subtitle: "For inquiries and cooperation." } },
    jobs: [ {title: "QA specialist", location: "Namangan", type: "Full-time"}, {title: "Frontend developer", location: "Tashkent / Remote", type: "Contract"}, {title: "Logistics coordinator", location: "Namangan", type: "Full-time"} ],
    contact: { eyebrow: "Contact", title: "Get in touch with us", name: "Your name", email: "Email", message: "Message", send: "Send", sent: "Message sent!", error: "An error occurred.", index: "Index", email_label: "Email", all: "All", apply: "Apply" },
    footer: { about: "MERRYMED FARM - Modern pharmaceutical company.", contact: "Contact", rights: "© 2026 MERRYMED FARM. All rights reserved.", old:"Created by ZeroEndTech team" },
    admin: { title: "Admin Panel", login: "Login", logout: "Logout", products: "Products", news: "News", gallery: "Gallery", add: "Add", edit: "Edit", delete: "Delete", save: "Save", cancel: "Cancel", confirm: "Are you sure?", email: "Email", password: "Password", loginFail: "Wrong email or password" }
  }
};
