export const TRANSLATIONS = {
  uz: {
    nav: { home: "Bosh sahifa", products: "Mahsulotlar", news: "Yangiliklar", gallery: "Galereya", jobs: "Ish o'rinlari", contact: "Bog'lanish", admin: "Admin", menu: "Menyuni ochish", close: "Menyuni yopish" },
    hero: { title: "MERRYMED FARM", subtitle: "YETAKCHI FARMATSEVTIKA KOMPANIYASI ga", new:"XUSH KELIBSIZ", add:"Biz, aholini maqbul narxlardagi yuqori sifatli dori vositalari bilan ta’minlashga intiluvchi, O’zbekistondagi eng yirik dori vositalari ishlab chiqaruvchilardan birimiz.", cta1: "Ko'proq ma'lumot", cta2: "Bog'lanish", eyebrow: "MERRYMED FARM" },
    home: { about_eyebrow: "", about_title: "Rasmiy saytimizga xush kelibsiz!", about_text: "«MERRYMED FARM» mas’uliyati cheklangan jamiyati 2010 yil yanvar oyida tashkil etilgan bo‘lib, bugungi kunda Respublikadagi eng yirik farmatsevtika korxonalarıdan biri hisoblanadi. «MERRYMED FARM» MCHJ ishlab chiqarish, saqlash, transport-logistika, marketing jarayonlarini to‘laligicha o‘zida qamrab olgan. Yuqori texnologiyali uskunalar va komponentlar, texnologik jarayonning barcha bosqichlarida axborotni kuzatish, yig’ish, qayta ishlash va chiqarishda, elektron tizimning maxsus talablarini ta’minlaydi. Korxonaning umumiy maydoni 14500m2 va ishlab chiqarish maydoni 11600m2 ni tashkil etadi.", mission: " Korxona dori vositalarini ishlab chiqarishga ixtisoslashgan. «MERRYMED FARM» MCHJ mamlakatda import o‘rnini bosishda zarur bo‘lgan 10 farmakologik guruhdagi 200 nomdan ortiq turli shakldagi dori vositalari, shu jumladan tabletkalar, kapsulalar, surtmalar, galen mahsulotlari, suspenziyalar, shamchalar, infuziya uchun eritmalar, in’eksiya uchun eritmalar, quruq kukun ko‘rinishidagi antibiotiklar, ko‘z tomchilari va boshqalarni ishlab chiqarish yo‘lga qo‘yilgan.", highlights_eyebrow: "Afzalliklar", highlights_title: "Bizning kuchli tomonlarimiz", products_eyebrow: "Mahsulotlar", products_title: "Asosiy toifalar", see_all: "Barchasini ko'rish", news_eyebrow: "Yangiliklar", news_title: "So'nggi yangilanishlar", go_news: "Yangiliklarga o'tish", gallery_eyebrow: "Galereya", gallery_title: "Ishlab chiqarishdan lavhalar", more: "Ko'proq" },
    highlights: [ {title: "Zamonaviy qadoqlash", text: "Saqlanish va xavfsizlikni ta'minlovchi yechimlar."}, {title: "Yangi texnologiyalar", text: "GMP talablariga javob beruvchi uskunalar."}, {title: "Noyob yondashuv", text: "Professionallikka asoslangan boshqaruv."} ],
    pages: { products: { title: "Mahsulotlar", subtitle: "Dori shakllari va toifalar." }, news: { title: "Yangiliklar", subtitle: "Kompaniya yangiliklari va e'lonlar." }, gallery: { title: "Galereya", subtitle: "Ishlab chiqarish lavhalar." }, jobs: { title: "Ish o'rinlari", subtitle: "Ochiq vakansiyalar." }, contact: { title: "Bog'lanish", subtitle: "Murojaat va hamkorlik uchun." } },
    jobs: [ {title: "QA mutaxassisi", location: "Namangan", type: "Full-time"}, {title: "Frontend developer", location: "Toshkent / Remote", type: "Contract"}, {title: "Logistika koordinatori", location: "Namangan", type: "Full-time"} ],
    contact: { eyebrow: "Bog'lanish", title: "Biz bilan aloqaga chiqing", name: "Ismingiz", email: "Email", message: "Xabar matni", send: "Yuborish", sent: "Xabaringiz yuborildi!", error: "Xatolik yuz berdi.", index: "Indeks", email_label: "Email", all: "Barchasi", apply: "Ariza topshirish" },
    footer: { about: "MERRYMED FARM - Zamonaviy farmatsevtika kompaniyasi.", contact: "Aloqa", rights: "© 2026 MERRYMED FARM. Barcha huquqlar himoyalangan.", old: "ZeroEndTech jamosi tomonidan yaratilgan" },
    admin: { title: "Admin Panel", login: "Kirish", logout: "Chiqish", products: "Mahsulotlar", news: "Yangiliklar", gallery: "Galereya", add: "Qo'shish", edit: "Tahrirlash", delete: "O'chirish", save: "Saqlash", cancel: "Bekor qilish", confirm: "Ishonchingiz komilmi?", email: "Email", password: "Parol", loginFail: "Email yoki parol noto'g'ri" }
  },
  ru: {
    nav: { home: "Главная", products: "Продукция", news: "Новости", gallery: "Галерея", jobs: "Вакансии", contact: "Контакты", admin: "Админ", menu: "Открыть меню", close: "Закрыть меню" },
    hero: { mer:"MERRYMED FARM", wel: "ДОБРО ПОЖАЛОВАТЬ в", lend:" ВЕДУЩУЮ ФАРМАЦЕВТИЧЕСКУЮ КОМПАНИЮ", add: "Мы один из крупнейших производителей лекарственных препаратов в Узбекистане стремящийся обеспечить население высококачественными препаратами по доступной цене.", cta1: "Подробнее", cta2: "Связаться", eyebrow: "MERRYMED FARM" },
    home: { about_eyebrow: "", about_title: "Добро пожаловать на наш сайт!", about_text: "Общество с ограниченной ответственностью «MERRYMED FARM» создано в январе 2010 года и на сегодняшний день считается крупнейшим фармацевтическим предприятием Республики. ООО «MERRYMED FARM» полностью охватывает процессы производства, хранения, транспортно-логистики, маркетинга. С помощью высокотехнологичного оборудования и электронных информационных систем управления обеспечивается контроль, сбор, сортировка, обработка и вывод информации на всех этапах технологического процесса. Общая площадь предприятия составляет 14 500 м2, производственная площадь – 11 600 м2.", mission: "Предприятие специализируется на производстве лекарственных средств. ООО «MERRYMED FARM» наладило производство более 200 наименований препаратов относящиеся к 10 фармакологическим группам в виде следующих лекрственных форм: таблетки, капсулы, мази, галеновые препараты, суспензии, суппозитории, растворы для инфузии, растворы для инъекции, антибиотики в виде сухого порошка, глазные капли и т.д.", highlights_eyebrow: "Преимущества", highlights_title: "Наши сильные стороны", products_eyebrow: "Продукция", products_title: "Основные категории", see_all: "Смотреть все", news_eyebrow: "Новости", news_title: "Последние обновления", go_news: "Перейти к новостям", gallery_eyebrow: "Галерея", gallery_title: "Моменты производства", more: "Больше" },
    highlights: [ {title: "Современная упаковка", text: "Решения, обеспечивающие сохранность и безопасность."}, {title: "Новые технологии", text: "Оборудование по стандартам GMP."}, {title: "Уникальный подход", text: "Управление на основе профессионализма."} ],
    pages: { products: { title: "Продукция", subtitle: "Лекарственные формы и категории." }, news: { title: "Новости", subtitle: "Новости и объявления компании." }, gallery: { title: "Галерея", subtitle: "Моменты производства." }, jobs: { title: "Вакансии", subtitle: "Открытые позиции." }, contact: { title: "Контакты", subtitle: "Для обращений и сотрудничества." } },
    jobs: [ {title: "QA специалист", location: "Наманган", type: "Full-time"}, {title: "Frontend разработчик", location: "Ташкент / Remote", type: "Contract"}, {title: "Координатор логистики", location: "Наманган", type: "Full-time"} ],
    contact: { eyebrow: "Контакты", title: "Свяжитесь с нами",  name: "Ваше имя", email: "Email", message: "Сообщение", send: "Отправить", sent: "Сообщение отправлено!", error: "Произошла ошибка.", index: "Индекс", email_label: "Email", all: "Все", apply: "Подать заявку" },
    footer: { about: "MERRYMED FARM - Современная фармкомпания.", contact: "Контакты", rights: "© 2026 MERRYMED FARM. Все права защищены.", old:"Создано командой ZeroEndTech" },
    admin: { title: "Админ панель", login: "Войти", logout: "Выход", products: "Продукция", news: "Новости", gallery: "Галерея", add: "Добавить", edit: "Изменить", delete: "Удалить", save: "Сохранить", cancel: "Отмена", confirm: "Вы уверены?", email: "Email", password: "Пароль", loginFail: "Неверный email или пароль" }
  },
  en: {
    nav: { home: "Home", products: "Products", news: "News", gallery: "Gallery", jobs: "Careers", contact: "Contact", admin: "Admin", menu: "Open menu", close: "Close menu" },
    hero: { wel: "", mery:"MERRYMED FARM", lend:" LEADING PHARMACEUTICAL COMPANY", add: "We are one of the largest manufacturers of medicines in Uzbekistan, aspiring to provide the population with high-quality medicines at an affordable price.", subtitle: "", cta1: "Learn more", cta2: "Contact us", eyebrow: "MERRYMED FARM" },
    home: { about_eyebrow: "", about_title: "Welcome to our official website!", about_text: "“MERRYMED FARM” LLC established in January 2010 and today is considered the largest pharmaceutical enterprise in the Republic. “MERRYMED FARM” LLC fully covers the processes of production, storage, transport and logistics, and marketing. With the help of high-tech equipment and electronic information management systems, we provide control, collection, sorting, processing and output of information at all stages of the technological process. The total area of the enterprise is 14,500 m2, the production area is 11,600 m2.", mission: "The company specializes in the production of medicines. MERRYMED FARM LLC has established the production of more than 200 types of drugs in 10 pharmacological groups, including tablets, capsules, ointments, herbal preparations, suspensions, infusions, injections, antibiotics in the form of dry powder, eye drops, etc.", highlights_eyebrow: "Advantages", highlights_title: "Our strengths", products_eyebrow: "Products", products_title: "Main categories", see_all: "View all", news_eyebrow: "News", news_title: "Latest updates", go_news: "Go to news", gallery_eyebrow: "Gallery", gallery_title: "Production moments", more: "More" },
    highlights: [ {title: "Modern packaging", text: "Solutions for safety and preservation."}, {title: "New technologies", text: "Equipment meeting GMP standards."}, {title: "Unique approach", text: "Management based on professionalism."} ],
    pages: { products: { title: "Products", subtitle: "Dosage forms and categories." }, news: { title: "News", subtitle: "Company news and announcements." }, gallery: { title: "Gallery", subtitle: "Production moments." }, jobs: { title: "Careers", subtitle: "Open positions." }, contact: { title: "Contact", subtitle: "For inquiries and cooperation." } },
    jobs: [ {title: "QA specialist", location: "Namangan", type: "Full-time"}, {title: "Frontend developer", location: "Tashkent / Remote", type: "Contract"}, {title: "Logistics coordinator", location: "Namangan", type: "Full-time"} ],
    contact: { eyebrow: "Contact", title: "Get in touch with us", name: "Your name", email: "Email", message: "Message", send: "Send", sent: "Message sent!", error: "An error occurred.", index: "Index", email_label: "Email", all: "All", apply: "Apply" },
    footer: { about: "MERRYMED FARM - Modern pharmaceutical company.", contact: "Contact", rights: "© 2026 MERRYMED FARM. All rights reserved.", old:"Created by ZeroEndTech team" },
    admin: { title: "Admin Panel", login: "Login", logout: "Logout", products: "Products", news: "News", gallery: "Gallery", add: "Add", edit: "Edit", delete: "Delete", save: "Save", cancel: "Cancel", confirm: "Are you sure?", email: "Email", password: "Password", loginFail: "Wrong email or password" }
  }
};
